Repository arduino/serial-discovery, pull requests merged in 2021-08, with the labels that each got.

#22 Update dependencies
  go.mod
  go.sum
  main.go
  sync.go
  sync_darwin.go
  sync_linux.go
  sync_windows.go
Labels: topic: code

#23 Reorganized project
  Taskfile.yml
  args/args.go
  main.go
  sync/sync.go
  sync/sync_darwin.go
  sync/sync_default.go
  sync/sync_linux.go
  sync/sync_windows.go
  sync/zsyscall_windows.go
  version/version.go
Labels: type: enhancement

#24 Handle closing of uevent reader gracefully
  go.mod
  go.sum
  sync/sync_linux.go
Labels: type: enhancement

#25 Fix `STOP` command not stopping discovery syncing
  sync/sync_darwin.go
Labels: type: imperfection

#26 Add "v" prefix to changelog generation regex
  .github/workflows/release-go-task.yml
Labels: topic: infrastructure, type: imperfection
